// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABIdV9GwjHX0UffJP__jaPKjTVZ9xkvAI',
    appId: '1:579180045068:web:c1cf567a0ef3259879df29',
    messagingSenderId: '579180045068',
    projectId: 'huewoo-c0b97',
    authDomain: 'huewoo-c0b97.firebaseapp.com',
    databaseURL:
        'https://huewoo-c0b97-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'huewoo-c0b97.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJiVdblA7x2BlpR93h3YG0nQr9rdrZ7mc',
    appId: '1:579180045068:android:81c28c64efe644e779df29',
    messagingSenderId: '579180045068',
    projectId: 'huewoo-c0b97',
    databaseURL:
        'https://huewoo-c0b97-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'huewoo-c0b97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFY3kyjxrpM1EGfe0SHOZ49ciMffiJLug',
    appId: '1:579180045068:ios:b1601c2dfc358bc679df29',
    messagingSenderId: '579180045068',
    projectId: 'huewoo-c0b97',
    databaseURL:
        'https://huewoo-c0b97-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'huewoo-c0b97.appspot.com',
    iosClientId:
        '579180045068-on3im9nlbjk9cen6raagvlf1ioss8esv.apps.googleusercontent.com',
    iosBundleId: 'com.example.huewoo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFY3kyjxrpM1EGfe0SHOZ49ciMffiJLug',
    appId: '1:579180045068:ios:b1601c2dfc358bc679df29',
    messagingSenderId: '579180045068',
    projectId: 'huewoo-c0b97',
    databaseURL:
        'https://huewoo-c0b97-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'huewoo-c0b97.appspot.com',
    iosClientId:
        '579180045068-on3im9nlbjk9cen6raagvlf1ioss8esv.apps.googleusercontent.com',
    iosBundleId: 'com.example.huewoo',
  );
}
